### PR TITLE
Fix ordering of "const unsafe fn"

### LINKED ISSUE #850: const unsafe fn is being reordered incorrectly
rustfmt will turn this:
```rust
const unsafe fn x() {}
```
into this:
```rust
unsafe const fn x() {}
```

However the latter causes a compile error since `const` must come before `unsafe`. This causes rustfmt to break working code. Even running rustfmt twice results in an error since the second code is invalid syntax.

### PR DESCRIPTION
**Pull request by Amanieu**
Fixes #850

### CODE REVIEW

**Comment by marcusklaas** [comment]
Could you add a test for this?

**Comment by Amanieu** [comment]
Done

**Comment by nrc** [comment]
Thanks for the PR! r+, but it needs a rebase before we can merge it.

**Comment by Amanieu** [comment]
Done

**Pull request merged**
