### PR TITLE
Fix installation instructions to use rustup

### PR DESCRIPTION
**Pull request by steveklabnik**
This is confusing a lot of people.

### CODE REVIEW

**Comment by crumblingstatue** [comment]
#1526 is still open, so maybe it is still not yet advised to install through rustup?

**Comment by topecongiro** [comment]
Would you please add an explanation that `rustfmt-preview` will be removed from the nightly component when there is a breaking change in `libsyntax`, and until rustfmt gets fixed, users must install rustfmt via `cargo install rustfmt-nightly`?

**Comment by anderejd** [comment]
Installing by rustup did not work for me. The way to use rustfmt with stable as default (what everyone outside the rust language core team should be nudged towards using!) is:

Installation:
`cargo +nightly install rustup-nightly`

Usage:
`cargo +nightly fmt`

Those two example command are all normal users need. Please put those two at the top of the readme.

**Comment by steveklabnik** [comment]
It will be on stable in the next release, incidentally

**Comment by topecongiro** [comment]
Since rustfmt 0.3.5 it started to depend on `rustc-ap-syntax` instead of `libsyntax` tied with rustc. This made rustfmt more resilient to internal changes inside rustc. As such, I think rustfmt will be available as component most of the time, so I am going to merge this.

@steveklabnik Thank you for improving the instruction!

**Pull request merged**
