### PR TITLE
visitor: A few file lines fixes

### PR DESCRIPTION
**Pull request by emilio**
This is on top of #1836, and fixes the issues I saw in bindgen.

### CODE REVIEW

**Comment by emilio** [comment]
r? @nrc 

cc @topecongiro

**Comment by topecongiro** [comment]
Nice, thanks for your PR!

**Comment by nrc** [comment]
r+, could you rebase please?

**Comment by emilio** [comment]
Huh, I'd have expected GH to be able to figure out this rebase. Done, thanks for the review! :)

**Comment by nrc** [comment]
Thank you!

**Pull request merged**
