### PR TITLE
Add howto for CLion / IntelliJ IDE integration

### PR DESCRIPTION
**Pull request by kellerkindt**

### CODE REVIEW

**Comment by otavio** [comment]
Hello, thank you for adding this piece of documentation. It is indeed very helpful for people trying to integrate it.

Would you mind if I do a minor request?

It'd be great if you could squash all the commits together so it provides an atomic change adding the new documentation, as it is indeed, a single logical change.

If you need any help in how to do that, I will be happy to assist you.

**Comment by kellerkindt** [comment]
Hi, didn't think about that. Is the current state the way you expected it to be? :)

**Comment by otavio** [comment]
Yes, it looks great 👍. Thanks!

**Comment by kellerkindt** [comment]
@otavio Sry, just re-pushed to remove the "other" committer, which was me on a host with another git  configuration. At least only one "person" is now mentioned for that commit :)

**Comment by otavio** [comment]
Great 👍 thanks again!

**Comment by nrc** [comment]
Thanks for the PR!

**Pull request merged**
