### PR TITLE
Don't generate V: { f: u8, // comment }

### LINKED ISSUE #2446: generating invalid code with comment inside record enum variant
This happens with default options, but only when the field line is shorter than heuristic width, so it doesn't happen often in practice.

code:

```rust
pub enum Volume {
  Var {
    f: u8, //
  }
}
```

output:

```rust
pub enum Volume {
    Var { f: u8, // },
}
```

### PR DESCRIPTION
**Pull request by radix**
Fixes #2446 

My only concern is that since this uses `contains_comment`, it also reformats the following code unnecessarily:

```rust
enum E {
    V { f: u8, /* hi */ }
}
```

to

```rust
enum E {
    V {
        f: u8, /* hi */
    }
}
```

I couldn't find any functions like "contains_trailing_comment" which would probably be more appropriate

### CODE REVIEW

**Comment by radix** [comment]
appveyor failure was a spurious network error. I dunno if there's a way to kick it...

**Comment by topecongiro** [comment]
@radix Thank you for you PR!

You could use `last_line_contains_single_line_comment` over `contains_comment`.

**Comment by radix** [comment]
thanks for the hint @topecongiro ! I've pushed a new revision and updated the test.

**Comment by topecongiro** [comment]
Thank you!

**Pull request merged**
