### PR TITLE
Format nested mathces properly.

### LINKED ISSUE #1371: Weird formatting for nested match
Input:
```rust
fn main() {
    Some(match type_ {
        sfEvtClosed => Closed,
        sfEvtResized => {
            let e = unsafe { *event.size.as_ref() };

            Resized {
                width: e.width,
                height: e.height,
            }
        }
        sfEvtLostFocus => LostFocus,
        sfEvtGainedFocus => GainedFocus,
        sfEvtTextEntered => {
            TextEntered {
                unicode: unsafe {
                    ::std::char::from_u32((*event.text.as_ref()).unicode)
                        .expect("Invalid unicode encountered on TextEntered event")
                },
            }
        }
        sfEvtKeyPressed => {
            let e = unsafe { event.key.as_ref() };

            KeyPressed {
                code: unsafe { ::std::mem::transmute(e.code) },
                alt: e.alt.to_bool(),
                ctrl: e.control.to_bool(),
                shift: e.shift.to_bool(),
                system: e.system.to_bool(),
            }
        }
        sfEvtKeyReleased => {
            let e = unsafe { event.key.as_ref() };

            KeyReleased {
                code: unsafe { ::std::mem::transmute(e.code) },
                alt: e.alt.to_bool(),
                ctrl: e.control.to_bool(),
                shift: e.shift.to_bool(),
                system: e.system.to_bool(),
            }
        }
    })
}

```

Output:
```rust
fn main() {
    Some(match type_ {
             sfEvtClosed => Closed,
             sfEvtResized => {
        let e = unsafe { *event.size.as_ref() };

        Resized {
            width: e.width,
            height: e.height,
        }
    }
             sfEvtLostFocus => LostFocus,
             sfEvtGainedFocus => GainedFocus,
             sfEvtTextEntered => {
            TextEntered {
                unicode: unsafe {
                    ::std::char::from_u32((*event.text.as_ref()).unicode)
                        .expect("Invalid unicode encountered on TextEntered event")
                },
            }
        }
             sfEvtKeyPressed => {
        let e = unsafe { event.key.as_ref() };

        KeyPressed {
            code: unsafe { ::std::mem::transmute(e.code) },
            alt: e.alt.to_bool(),
            ctrl: e.control.to_bool(),
            shift: e.shift.to_bool(),
            system: e.system.to_bool(),
        }
    }
             sfEvtKeyReleased => {
        let e = unsafe { event.key.as_ref() };

        KeyReleased {
            code: unsafe { ::std::mem::transmute(e.code) },
            alt: e.alt.to_bool(),
            ctrl: e.control.to_bool(),
            shift: e.shift.to_bool(),
            system: e.system.to_bool(),
        }
    }
         })
}

```

rustfmt 0.8.0

### PR DESCRIPTION
**Pull request by topecongiro**
This PR closes #1371.

Input:
```rust
fn main() {
    Some(match type_ {
        sfEvtClosed => Closed,
        sfEvtResized => {
            let e = unsafe { *event.size.as_ref() };

            Resized {
                width: e.width,
                height: e.height,
            }
        }
        sfEvtLostFocus => LostFocus,
        sfEvtGainedFocus => GainedFocus,
        sfEvtTextEntered => {
            TextEntered {
                unicode: unsafe {
                    ::std::char::from_u32((*event.text.as_ref()).unicode)
                        .expect("Invalid unicode encountered on TextEntered event")
                },
            }
        }
        sfEvtKeyPressed => {
            let e = unsafe { event.key.as_ref() };

            KeyPressed {
                code: unsafe { ::std::mem::transmute(e.code) },
                alt: e.alt.to_bool(),
                ctrl: e.control.to_bool(),
                shift: e.shift.to_bool(),
                system: e.system.to_bool(),
            }
        }
        sfEvtKeyReleased => {
            let e = unsafe { event.key.as_ref() };

            KeyReleased {
                code: unsafe { ::std::mem::transmute(e.code) },
                alt: e.alt.to_bool(),
                ctrl: e.control.to_bool(),
                shift: e.shift.to_bool(),
                system: e.system.to_bool(),
            }
        }
    })
}
```
Output:
```rust
fn main() {
    Some(match type_ {
             sfEvtClosed => Closed,
             sfEvtResized => {
                 let e = unsafe { *event.size.as_ref() };

                 Resized {
                     width: e.width,
                     height: e.height,
                 }
             }
             sfEvtLostFocus => LostFocus,
             sfEvtGainedFocus => GainedFocus,
             sfEvtTextEntered => {
                 TextEntered {
                     unicode:
                         unsafe {
                             ::std::char::from_u32((*event.text.as_ref()).unicode)
                                 .expect("Invalid unicode encountered on TextEntered event")
                         },
                 }
             }
             sfEvtKeyPressed => {
                 let e = unsafe { event.key.as_ref() };

                 KeyPressed {
                     code: unsafe { ::std::mem::transmute(e.code) },
                     alt: e.alt.to_bool(),
                     ctrl: e.control.to_bool(),
                     shift: e.shift.to_bool(),
                     system: e.system.to_bool(),
                 }
             }
             sfEvtKeyReleased => {
                 let e = unsafe { event.key.as_ref() };

                 KeyReleased {
                     code: unsafe { ::std::mem::transmute(e.code) },
                     alt: e.alt.to_bool(),
                     ctrl: e.control.to_bool(),
                     shift: e.shift.to_bool(),
                     system: e.system.to_bool(),
                 }
             }
         })
}
```

### CODE REVIEW

**Comment by topecongiro** [comment]
This PR closes #1395 and #1456 as well.

**Comment by nrc** [comment]
This looks great, thank you! Could you add some tests please?

**Comment by topecongiro** [comment]
Hi, I added tests & rebased.

**Comment by nrc** [comment]
Thansk!

**Pull request merged**
