### PR TITLE
Use getters to access `Span` fields

### PR DESCRIPTION
**Pull request by petrochenkov**
Required for merging https://github.com/rust-lang/rust/pull/43968

r? @nrc

### CODE REVIEW

**Comment by nrc** [comment]
r+

This is the upstream branch: https://github.com/rust-lang-nursery/rustfmt/tree/span

And the RLS branch is https://github.com/rust-lang-nursery/rls/tree/rustfmt-span

**Comment by petrochenkov** [comment]
@nrc 
https://github.com/rust-lang/rust/pull/44028 was just merged.
Could you rebase https://github.com/rust-lang-nursery/rls/tree/rustfmt-span on master?

**Comment by nrc** [comment]
@petrochenkov rustfmt and rls branches are both rebased

**Comment by petrochenkov** [comment]
Rebased.
https://github.com/rust-lang/rust/pull/43968 was merged yesterday, so this PR can be merged directly now.

**Comment by nrc** [comment]
I merged this after a rebase. And it is getting pulled into Rust via the RLS via https://github.com/rust-lang/rust/pull/44176

**Pull request closed without merging**
