### PR TITLE
force a newline after the `if` condition if there is a different indentation level

### LINKED ISSUE #3038: Should split opening brace of if let onto new line for long expressions
Before:
```rust
            if let Some(last_tbody) = node.rev_children()
                .find(|n| n.is::<HTMLTableSectionElement>() && n.local_name() == &local_name!("tbody")) {
                    last_tbody.upcast::<Node>().AppendChild(new_row.upcast::<Node>())
                                               .expect("InsertRow failed to append first row.");
                }
```
After:
```rust
            if let Some(last_tbody) = node
                .rev_children()
                .filter_map(DomRoot::downcast::<Element>)
                .find(|n| {
                    n.is::<HTMLTableSectionElement>() && n.local_name() == &local_name!("tbody")
                }) {
                last_tbody
                    .upcast::<Node>()
                    .AppendChild(new_row.upcast::<Node>())
                    .expect("InsertRow failed to append first row.");
            }
```
I would expect this instead:
```rust
            if let Some(last_tbody) = node
                .rev_children()
                .filter_map(DomRoot::downcast::<Element>)
                .find(|n| {
                    n.is::<HTMLTableSectionElement>() && n.local_name() == &local_name!("tbody")
                })
            {
                last_tbody
                    .upcast::<Node>()
                    .AppendChild(new_row.upcast::<Node>())
                    .expect("InsertRow failed to append first row.");
            }
```

### PR DESCRIPTION
**Pull request by scampi**
close #3038

### CODE REVIEW

**Comment by otavio** [comment]
LGTM

**Comment by scampi** [comment]
There is some problem compiling `ust-semverver` right from the start. I tried locally and it happened with the nightly of 2018-10-15.

```
error[E0308]: mismatched types
   --> src/semcheck/mismatch.rs:183:22
    |
183 |                     (Some(a), Some(b)) if self.check_substs(a.skip_binder().substs,
    |                      ^^^^^^^ expected struct `rustc::ty::Binder`, found enum `std::option::Option`
    |
    = note: expected type `rustc::ty::Binder<rustc::ty::ExistentialTraitRef<'_>>`
               found type `std::option::Option<_>`
                                                                                
error[E0308]: mismatched types
   --> src/semcheck/mismatch.rs:183:31
    |
183 |                     (Some(a), Some(b)) if self.check_substs(a.skip_binder().substs,
    |                               ^^^^^^^ expected struct `rustc::ty::Binder`, found enum `std::option::Option`
    |
    = note: expected type `rustc::ty::Binder<rustc::ty::ExistentialTraitRef<'_>>`
               found type `std::option::Option<_>`
                                                                                
error[E0308]: mismatched types
   --> src/semcheck/mismatch.rs:183:22
    |
183 |                     (Some(a), Some(b)) if self.check_substs(a.skip_binder().substs,
    |                      ^^^^^^^ expected struct `rustc::ty::Binder`, found enum `std::option::Option`
    |
    = note: expected type `rustc::ty::Binder<rustc::ty::ExistentialTraitRef<'_>>`
               found type `std::option::Option<_>`
                                                                                
error[E0308]: mismatched types
   --> src/semcheck/mismatch.rs:183:31
    |
183 |                     (Some(a), Some(b)) if self.check_substs(a.skip_binder().substs,
    |                               ^^^^^^^ expected struct `rustc::ty::Binder`, found enum `std::option::Option`
    |
    = note: expected type `rustc::ty::Binder<rustc::ty::ExistentialTraitRef<'_>>`
               found type `std::option::Option<_>`
```

**Comment by scampi** [comment]
@otavio not rustfmt, `rust-semverver` is failing ;o)

**Comment by scampi** [comment]
@otavio the problem is unrelated to `rustfmt`, `rust-semverver` cannot be compiled with nightly at the moment. I have seen other PRs fail because of that.

**Pull request merged**
