### PR TITLE
config: Introduce a mergeable config

### PR DESCRIPTION
**Pull request by kamalmarhubi**
This pull request introduces a mergeable config abstraction, and uses it for the `verbose` and `skip_children` configuration options.

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
@nrc, this is *much* nicer than #795 imo :-)

**Comment by nrc** [comment]
What is the advantage of using a `PartialConfig` over just initialising a regular Config with the defaults and then overriding them?

**Comment by kamalmarhubi** [comment]
Part of the motivation was to tidy up how `write_mode` is passed around and dealt wtih. I realise I didn't put up that change; pushed it up in case you want to see it. On reflection I don't feel too strongly about this change, so it's up to you. The `write_mode` setting is kind of overloaded in a way that this doesn't fix anyway.

**Comment by kamalmarhubi** [comment]
Anyway, feel free to look over the changes moving `write_mode` to only come from `Config`. I'll hold off fixing conflicts till I hear something positive / negative about the change. Thanks!

**Comment by kamalmarhubi** [comment]
(I think I was [refactoring as a way to understand code](http://composition.al/blog/2015/12/29/refactoring-as-a-way-to-understand-code/) here.)

**Comment by nrc** [comment]
So, having the write mode be part of the config sounds like a good change. However, I don't see that using the builder pattern for the config is a pre-req for it. Maybe I'm missing something, but couldn't you just set it to some default and then reset it later in the right places?

**Comment by kamalmarhubi** [comment]
Yeah, the config stuff isn't necessary. I'll send another PR tomorrow that gets the write_mode read solely from the config.

**Comment by kamalmarhubi** [comment]
#812 replaces this.

**Pull request closed without merging**
