### PR TITLE
Add spaces_within_square_brackets config option.

### PR DESCRIPTION
**Pull request by Rantanen**
Enabling the config enforces spaces within various array/slice brackets.

While implementing this one, I realized I had completely missed the `budget` calculations in the previous PRs as well. This one doesn't implement them either for now.

I'll look into the budget calculations for all the 3 `spaces_within_*` options next. Unless I'm instructed otherwise, I'll add the square brackets budget calculation fixes to this PR if this is still open by the time I figure out how the budgets are calculated and I'll send the parentheses/angle brackets fixes as a new PR. Otherwise I'll send all of them as a single new PR.

### CODE REVIEW

**Comment by Rantanen** [comment]
That was easier than I expected.

The `[ i32; 123 ]` syntax didn't seem to use budget calculations for splitting the pair (only the LHS) so no tests for that.

If there are some other cases where [] should affect budget calculations that aren't covered by the tests, please notify me and I'll add those as tests as well.

**Comment by nrc** [comment]
Looks good to me.

General point for this style - does it work with macros, e.g., will `vec![ foo ]` get formatted properly?

**Comment by Rantanen** [comment]
There is a test for `let v = vec![1, 2, 3];` -> `let v = vec![ 1, 2, 3 ];` if that's what you mean.

I should probably add some other macro tests, such as `println!()` to the other `spaces_within_*` rules at some point.

Currently I'm a bit curious about the line length rules. How complete are those? I'm having trouble getting following to format correctly:

```rust
struct loooooooo...ooooooong< A, B, C > {
//                          100 chars ^ ^ 102 chars
}
```

It feels like the budget calculations are ignoring the `{` which ends up exceeding the 100-character limit. The generic parameters wrap only if the `>` exceeds the 100-character limit. Felt like this is existing issue even without the `spaces_within_angle_brackets` option, but would like a confirmation. It could be I'm just failing to grasp the actual wrapping rules.

**Comment by nrc** [comment]
> There is a test for let v = vec![1, 2, 3]; -> let v = vec![ 1, 2, 3 ]; if that's what you mean.

It was, I must have missed it. Glad that works :-)

> Currently I'm a bit curious about the line length rules...

They are meant to be pretty complete and we should warn when we get it wrong. It sounds like you found a bug. If you could report with a test case (and whether you need the `spaces_within_angle_brackets` option) that would be useful, thanks!

**Pull request merged**
