### PR TITLE
config: Introduce RunConfig for config related to a single run

### PR DESCRIPTION
**Pull request by kamalmarhubi**
config: Introduce RunConfig for config related to a single run

This pull request introduces a `RunConfig` struct, and threads it
through all libraries, binaries, and tests. It carries configuration
related to a single run of `rustfmt`, as distinct from configuration
read in from the `rustfmt.toml` file. The `verbose` and `skip-children`
settings are moved to `RunConfig`.

Other examples of such per-run settings:
 - the `write_mode` override
 - line ranges to restrict formatting to; see #434

refs #434

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
Thinking about this a bit more, it might not be the right abstraction. Merging into a single config that gets threaded around seems better. Going to sleep on it.

**Comment by nrc** [comment]
I like the sound of the alternative you describe better - sounds like less complexity.

**Comment by kamalmarhubi** [comment]
Yeah, I think so too. The realisation came up while trying to move `write_mode` into `RunConfig`. It was a lot more work than seemed reasonable!

I'll try and put together a PR with the alternative today so that I can actually start on #434!

**Comment by kamalmarhubi** [comment]
Closing in favor of #801.

**Pull request closed without merging**
