### PR TITLE
Fix #563 (OP)

### LINKED ISSUE #563: Disappearing comment
```diff
     if expando.ptr.is_null() {
-        (*bp).code_ = 0 /* OkCode */;
+        (*bp).code_ = 0;
         return true;
     }
```

### PR DESCRIPTION
**Pull request by cassiersg**

### CODE REVIEW

**Comment by marcusklaas** [comment]
Hey Gaetan, good to see you again! This makes the comment situation a bit better. Personally I don't think these comments look great in between the expr and the semicolon though. Could we consider moving them behind the statement? For example:
```rust
let x = some_expr() /* comment */;
```
would become
```rust
let x = some_expr(); // comment
```

**Comment by cmr** [comment]
@cassiersg Can you make the commit message more descriptive? It should be able to stand alone as an explanation of why the changes were made without refering to the issue tracker.

**Comment by nrc** [comment]
@cassiersg, @marcusklaas should we land this PR as is or wait for something better?

**Comment by cassiersg** [comment]
There is no longer inerest (I think) to land this as-is, since it doesn't change the output of rustfmt (the comment doesn't disappear anymore due to another PR already merged).
I think we can leave the formatting as it is now (ie comments just before `;` does not disappear but are not "well" formatted either. (I feel this is a very rare case.)

**Pull request closed without merging**
