### PR TITLE
Format code block in comment

### LINKED ISSUE #554: Format code block in doc comment
`````` Diff
diff --git a/src/lib.rs b/src/lib.rs
index f07c890..5e5ab58 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1,12 +1,14 @@
 //! Library for manipulating Game Maker Studio's "data.win" (GEN8) data files.
 //!
-//! Typical usage consists of reading [GameData](struct.GameData.html) from a file, doing stuff with it,
+//! Typical usage consists of reading [GameData](struct.GameData.html) from a
+//! file, doing stuff with it,
 //! then writing it back to a file.
 //!
 //! Example:
 //!
 //! ```no_run
-//! let mut game_data = rgmk::GameData::from_file("data.win").expect("Failed to open data.win");
+//! let mut game_data = rgmk::GameData::from_file("data.win").expect("Failed to
+//! open data.win");
 //! game_data.strings.strings[0] = "NYEH HEH HEH!".into();
 //! game_data.save_to_file("data.win").expect("Failed to save data.win");
 //! ```
``````

Now the generated documentation looks like this:

### LINKED ISSUE #1695: format rust code examples inside docs
is there a way to format the code examples inside the comment blocks?

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #554.
Closes #1695.

### CODE REVIEW

**Comment by killercup** [comment]
Awesome! Does this work with lines starting with `#` (to hide them in rustdoc's rendered output)?

**Comment by nrc** [comment]
Nice!

**Comment by topecongiro** [comment]
@killercup This does not work with lines starting with `#`, they will not be formatted. I will create a follow up PR to fix it.

**Comment by killercup** [comment]
Cool. It might be a bit tricky to format the hidden lines while also making
the visible ones look correctly indented. Let me know if you need some
weird test cases!

Seiichi Uchida <notifications@github.com> schrieb am Mi. 27. Dez. 2017 um
11:47:

**Pull request merged**
