### PR TITLE
test cargo fmt --all -- --check returns success after formatting

### PR DESCRIPTION
**Pull request by gnzlbg**
Adds test for the failure in #2787 , doesn't fix anything.

### CODE REVIEW

**Comment by nrc** [comment]
Looks good thanks, but as expected, we now fail testing for stdsimd, so could you move that to the expect to fail list please?

**Comment by gnzlbg** [comment]
Yes, sorry, I was just checking why on failure travis was still reporting success (it seems like `$0` in the `if`s was reporting the exit code of `tee` which is always success... my bad...).

**Comment by gnzlbg** [comment]
I've tried to fix chalk by making it build, but it seems that it lacks permissions to generate the files on CI for whatever reason. I think that to make chalk pass fixing #2789 is probably a better way forward.

**Comment by nrc** [comment]
Thanks!

**Pull request merged**
