### PR TITLE
Add --rustfmt-binary option to cargo-fmt

### PR DESCRIPTION
**Pull request by casey**
Points to the `rustfmt` binary to invoke. Defaults to `rustfmt` to
preserve the old behavior.

This is particularly useful when debugging rustfmt itself, since you
can use `cargo fmt --rustfmt-binary target/release/rustfmt` to use
your rustfmt with local changes.

`--rustfmt-binary` might be too long, I was also considering just
`--binary` or `--rustfmt`.

### CODE REVIEW

**Comment by nrc** [comment]
I'm not entirely sure that this is desirable - given that you want to run `cargo fmt --rustfmt-binary foo`, why don't you just run `foo`? (Or, precisely, `foo src/lib.rs`).

**Comment by casey** [comment]
I was finding it useful for testing, since then one can easily run a rustfmt build on an entire crate, instead of just a single file.

**Comment by sinkuu** [comment]
`rustfmt src/lib.rs` recurses into submodules.

**Comment by casey** [comment]
Oh, I didn't know that. In that case I think this can be closed.

**Pull request closed without merging**
