### PR TITLE
Add ignore config option

### LINKED ISSUE #705: ignore certain directories
Is there a way to ignore certain directories?
Like configuration in rustfmt.tml or a commandline switch?

### LINKED ISSUE #2444: Add an option to disable formatting git submodules
For example, if you run `cargo fmt` under rustc repository it will format submodules (clippy, miri, rls and rust-installer) and make them dirty. It would be nice if `cargo-fmt` could somehow detect submodules and skip them.

### PR DESCRIPTION
**Pull request by topecongiro**
This PR adds `ignore` config option, which lets users to tell rustfmt to skip formatting the specified files and directories. The current implementation is not as smart as `.gitignore`, but should get the job done.

For example, with the following config file, rustfmt will ignore `src/types.rs`,
`src/foo/bar.rs` and every file under `examples/` directory.

```toml
[ignore]
files = [
    "src/types.rs",
    "src/foo/bar.rs",
]
directories = [
    "examples",
]
```

Closes #705.
Closes #2444.

### CODE REVIEW

**Comment by topecongiro** [comment]
Thank you for the review! I have update the PR so that we can just have a single list.

After rethinking about this, I think we do not need to distinguish whether the given path is a file or a directory - just checking `file.starts_with(path)` seems ok.

**Comment by nrc** [comment]
Thanks!

**Comment by HarrisonMc555** [comment]
Would it be possible to add some more "intelligence" to this feature (like `.gitignore`)?

For example, I have a directory that contains several cargo projects, each of which has their own externally-supplied test files. I don't want to run `rustfmt` on these test files.

If I add a `rustfmt.toml` file to the outer directory with the line `ignore = ["tests"]`, then it won't ignore anything. I have to put that file in the individual sub-directory (project) that I want to use it for.

It appears (from several tests that I ran) that the file/directory name specified in the `ignore` option in `rustfmt.toml` needs to be found in the **same directory** as the `rustfmt.toml` in question. Could we change this to be a recursive check? I.e. if a file/directory in the same directory as `rustfmt.toml` **or** a file/directory in any subdirectories matched it would be ignored?

I'm just getting started with rust so I'm not sure if I could make the changes myself, but if someone gave me some pointers I might try my hand and see if I could get it to work.

**Comment by nrc** [comment]
> Would it be possible to add some more "intelligence" to this feature (like .gitignore)?

Possibly. Could you open an issue and we could try to hash out a design.

**Pull request merged**
