### PR TITLE
Add fn_arg_one_line option

### PR DESCRIPTION
**Pull request by erikjohnston**
If set, arguments will be kept on one line if they fit. Currently only applies when `fn_args_layout` is set to `Block`. 

Addresses: #708

--

This PR also fixes a bug where newlines were inserted in-between argument brackets when there were no arguments and `fn_args_layout` was set to `Block`.

Example of bug:

```rust
fn foo(

) {
}
```

--

I'm unsure about a few things:
- Should this be on by default? I left it off to keep existing behaviour the same, but it doesn't look particularly nice as is.
- Should this even be its own option? Should it be part of `fn_args_layout`?
- The option name/description can probably be improved.

Hopefully none of those questions affect the implementation though.

### CODE REVIEW

**Comment by erikjohnston** [comment]
I'm also unsure whether this affects: https://github.com/erikjohnston/rustfmt/blob/57847e451af3d0057f36f61c357f5c451b4ac7ed/src/items.rs#L1566-L1569

And there should also probably be tests for how this interacts with `fn_args_paren_newline`

**Comment by marcusklaas** [comment]
Thanks for the PR! I was wondering: is this option equivalent to increasing `fn_call_width` to `max_width`?

**Comment by erikjohnston** [comment]
@marcusklaas I have to confess I completely missed the `fn_call_width` option :)

It's not equivalent in the sense that if you set `fn_args_layout` to `Block` then the args are *always* put on a new line irrespective of their width. The existence of the `fn_call_width` option makes me lean further towards considering the current behaviour buggy, and to simply make `Block` option respect the specified width, rather than adding yet another option.

**Comment by nrc** [comment]
Clarifying: this is about function definitions, whereas `fn_call_width` only affects function calls? (we should clarify this in the config docs, btw).

This new option creates two variants on the `Block` layout for function defs - a variation where we try to fit on one line, and if that fails, use block layout, and a variation that always uses block layout?

It looks to me like we should rationalise the fn args options - it looks to me that there are a bunch which will overlap badly or at least be confusing. I guess that is kind of orthogonal to this PR.

But, I think the right approach here is to add options to StructLitStyle - Block for the behaviour with this PR and BlockAlways for the previous behaviour. It might also be worth combining this with `MultilineStyle`. Or I guess, for now, just use `MultilineStyle` rather than a bool.

**Comment by erikjohnston** [comment]
> This new option creates two variants on the `Block` layout for function defs - a variation where we try to fit on one line, and if that fails, use block layout, and a variation that always uses block layout?

That pretty much sums it up.

> It looks to me like we should rationalise the fn args options - it looks to me that there are a bunch which will overlap badly or at least be confusing. I guess that is kind of orthogonal to this PR.

Yeah, I spent a while trying to figure out if there was already an option to do this fwiw.

> But, I think the right approach here is to add options to StructLitStyle - Block for the behaviour with this PR and BlockAlways for the previous behaviour. It might also be worth combining this with MultilineStyle. Or I guess, for now, just use MultilineStyle rather than a bool.

Is this suggesting two options? First is to instead extend `fn_args_layout` to take `[Visual|Block|BlockAlways]` and the second is to piggy back off of `struct_lit_multiline_style [PreferSingle|ForceMulti]`? I'm mildly in favour of the former over the latter, but I don't really mind either way. (If no one shouts I'll implement it like that, though that won't be until Wednesday/Thursday at the earliest)

**Comment by nrc** [comment]
> Is this suggesting two options?

I meant to do one or the other, not both, and I'm not sure which will work out best. Either extend `StructLitStyle` (I think probably best to make a new enum `FnArgStyle`) or add a new option which takes a `MultilineStyle`. But not both :-)

**Comment by erikjohnston** [comment]
Ah, that's what I meant to say! :)  (I should really not be allowed to respond to PR comments after midnight...)

**Comment by nrc** [comment]
Thanks for the changes! Sorry it took a while for me to merge - GitHub doesn't notify when you push commits, only if you comment.

**Comment by erikjohnston** [comment]
Hi, thanks! Sorry for not commenting, I got distracted trying to track down some bad formatting if the generics list was long, but I think its completely orthogonal to this PR.

**Pull request merged**
