### PR TITLE
Put rhs of assignment on the next line if it fits in a single line

### LINKED ISSUE #1391: Constants with long identifiers and type casts have poor formatting

### PR DESCRIPTION
**Pull request by topecongiro**
*EDIT*: Please see the next comment.

This PR puts the rhs of assignement on the next line when putting next to `lhs = ` will cause rhs to go multi line, but putting on the next line makes it fits in a single line.

For example, instead of the next output,
```rust
let one_line_len = rewrites.iter().fold(0, |a, r| a + first_line_width(r)) +
    parent_rewrite.len(); 
```
we format to the following:
```rust
let one_line_len =
    rewrites.iter().fold(0, |a, r| a + first_line_width(r)) + parent_rewrite.len(); 
```
For more examples, please take a look at [the diffs](https://github.com/rust-lang-nursery/rustfmt/pull/1745/commits/fe6ef1e0523cfe1ec7a77b0e21079e7bf548fa44).

Closes #1391.

### CODE REVIEW

**Comment by topecongiro** [comment]
After reveiwing this PR by myself, what I did initially seemed wrong.
I changed this PR to only put rhs of assignment on the next line if it is cast or type annotation.

**Comment by nrc** [comment]
> This PR puts the rhs of assignement on the next line when putting next to lhs = will cause rhs to go multi line, but putting on the next line makes it fits in a single line.

At first blush, this sounds like a good heuristic. Why did you decide you didn't like this approach? Do you have an example of where it gives bad formatting?

**Comment by topecongiro** [comment]
These are the diffs from the first attempt.
```diff
-    block_flow.base.stacking_relative_position_of_display_port = self.base
-        .stacking_relative_position_of_display_port;
+    block_flow.base.stacking_relative_position_of_display_port =
+        self.base.stacking_relative_position_of_display_port;

-    block_flow.base.stacking_relative_position_of_display_port = self.base
-        .stacking_relative_position_of_display_port;
+    block_flow.base.stacking_relative_position_of_display_port =
+        self.base.stacking_relative_position_of_display_port;

-    let (error_summary, file_map, _report) = format_input::<io::Stdout>(input, &config, None)
-        .unwrap();
+    let (error_summary, file_map, _report) =
+        format_input::<io::Stdout>(input, &config, None).unwrap();

-    let (error_summary, _file_map, _report) = format_input::<io::Stdout>(input, &config, None)
-        .unwrap();
+    let (error_summary, _file_map, _report) =
+        format_input::<io::Stdout>(input, &config, None).unwrap();

-    let (_error_summary, file_map, report) = format_input::<io::Stdout>(input, &config, None)
-        .unwrap();
+    let (_error_summary, file_map, report) =
+        format_input::<io::Stdout>(input, &config, None).unwrap();

-    let very_long_variable_name = (a + first + simple + test + AAAAAAAAAAAAA +
-                                       BBBBBBBBBBBBBBBBB + b + c);
+    let very_long_variable_name =
+        (a + first + simple + test + AAAAAAAAAAAAA + BBBBBBBBBBBBBBBBB + b + c);

-    let is_internalxxxx = self.codemap.span_to_filename(s) ==
-        self.codemap.span_to_filename(m.inner);
+    let is_internalxxxx =
+        self.codemap.span_to_filename(s) == self.codemap.span_to_filename(m.inner);

-    let range = (111111111 + 333333333333333333 + 1111 + 400000000000000000)..
-        (2222 + 2333333333333333);
+    let range =
+        (111111111 + 333333333333333333 + 1111 + 400000000000000000)..(2222 + 2333333333333333);

-    let slightly_longer_trait = yyyyyyyyy +
-        yyyyyyyyyyy as SomeTraitYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY;
+    let slightly_longer_trait =
+        yyyyyyyyy + yyyyyyyyyyy as SomeTraitYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY;

-    let y = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
-        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb;
+    let y =
+        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb;

-const FILE_GENERIC_READ: DWORD = STANDARD_RIGHTS_READ | FILE_READ_DATA | FILE_READ_ATTRIBUTES |
-    FILE_READ_EA | SYNCHRONIZE;
+const FILE_GENERIC_READ: DWORD =
+    STANDARD_RIGHTS_READ | FILE_READ_DATA | FILE_READ_ATTRIBUTES | FILE_READ_EA | SYNCHRONIZE;

-    let very_long_variable_name = (a + first + simple + test + AAAAAAAAAAAAA +
-                                       BBBBBBBBBBBBBBBBB + b + c);
+    let very_long_variable_name =
+        (a + first + simple + test + AAAAAAAAAAAAA + BBBBBBBBBBBBBBBBB + b + c);

-    let is_internalxxxx = self.codemap.span_to_filename(s) ==
-        self.codemap.span_to_filename(m.inner);
+    let is_internalxxxx =
+        self.codemap.span_to_filename(s) == self.codemap.span_to_filename(m.inner);

-    let range = (111111111 + 333333333333333333 + 1111 + 400000000000000000)..
-        (2222 + 2333333333333333);
+    let range =
+        (111111111 + 333333333333333333 + 1111 + 400000000000000000)..(2222 + 2333333333333333);

-    let slightly_longer_trait = yyyyyyyyy +
-        yyyyyyyyyyy as SomeTraitYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY;
+    let slightly_longer_trait =
+        yyyyyyyyy + yyyyyyyyyyy as SomeTraitYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY;

-    let y = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
-        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb;
+    let y =
+        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb;

-const FILE_GENERIC_READ: DWORD = STANDARD_RIGHTS_READ | FILE_READ_DATA | FILE_READ_ATTRIBUTES |
-    FILE_READ_EA | SYNCHRONIZE;
+const FILE_GENERIC_READ: DWORD =
+    STANDARD_RIGHTS_READ | FILE_READ_DATA | FILE_READ_ATTRIBUTES | FILE_READ_EA | SYNCHRONIZE;

-                let is_internal = codemap.span_to_filename(item.span) ==
-                    codemap.span_to_filename(sub_mod.inner);
+                let is_internal =
+                    codemap.span_to_filename(item.span) == codemap.span_to_filename(sub_mod.inner);

-                let alt_block_sep = String::from("\n") +
-                    &shape.indent.block_only().to_string(context.config);
+                let alt_block_sep =
+                    String::from("\n") + &shape.indent.block_only().to_string(context.config);

-        let alt_block_sep = String::from("\n") +
-            &shape.indent.block_only().to_string(context.config);
+        let alt_block_sep =
+            String::from("\n") + &shape.indent.block_only().to_string(context.config);

-        let alt_block_sep = String::from("\n") +
-            &shape.indent.block_only().to_string(context.config);
+        let alt_block_sep =
+            String::from("\n") + &shape.indent.block_only().to_string(context.config);

-            let has_pre_comment = trimmed_pre_snippet.contains("//") ||
-                trimmed_pre_snippet.contains("/*");
+            let has_pre_comment =
+                trimmed_pre_snippet.contains("//") || trimmed_pre_snippet.contains("/*");

-    let one_line_len = rewrites.iter().fold(0, |a, r| a + first_line_width(r)) +
-        parent_rewrite.len();
+    let one_line_len =
+        rewrites.iter().fold(0, |a, r| a + first_line_width(r)) + parent_rewrite.len();

-    let multi_line_arg_str = arg_str.contains('\n') ||
-        arg_str.chars().last().map_or(false, |c| c == ',');
+    let multi_line_arg_str =
+        arg_str.contains('\n') || arg_str.chars().last().map_or(false, |c| c == ',');

-            let multi_line_overhead = indent.width() + result.len() +
-                if newline_brace { 2 } else { 4 };
+            let multi_line_overhead =
+                indent.width() + result.len() + if newline_brace { 2 } else { 4 };

**Comment by nrc** [comment]
> These are the diffs from the first attempt

They look like an improvement to me :-)

**Comment by topecongiro** [comment]
I kind of disliked wasting the spaces on the right hand side of `=`, but if you think they improves formatting, I am happy to use the first attempt. I will rebase shortly.

**Comment by nrc** [comment]
IMO, I think it is better to waste the space on the right (which is not too bad) and keep the rhs all on one line. This also means that the line-breaking reflects the precedence of operations.

**Comment by topecongiro** [comment]
> This also means that the line-breaking reflects the precedence of operations.
I see. Thank you for clarifying!

**Comment by topecongiro** [comment]
I have changed this PR back to the first version.

**Comment by nrc** [comment]
Thanks, looks great!

**Pull request merged**
