### PR TITLE
Fix build with rust nightly by updating try block syntax.

### PR DESCRIPTION
**Pull request by zachlute**
This is a version of #2964 that doesn't change all the line endings. Sorry about that.

It still seems to be failing some tests. One of them seems to be related to this change in that it's reformatting the line I changed, but...I don't understand why it's different than the previous behavior.

The rest seem unrelated to this change?

### CODE REVIEW

**Comment by zachlute** [comment]
The related test failure is this one:
```
---- test::self_tests stdout ----

Mismatch at src\expr.rs:318:
         // satisfy our width restrictions.
         ast::ExprKind::InlineAsm(..) => Some(context.snippet(expr.span).to_owned()),
         ast::ExprKind::TryBlock(ref block) => {
-            if let rw @ Some(_) = rewrite_single_line_block(
-                context,
-                "try ",
-                block,
-                Some(&expr.attrs),
-                None,
-                shape,
-            ) {
+            if let rw @ Some(_) =
+                rewrite_single_line_block(context, "try ", block, Some(&expr.attrs), None, shape)
+            {
                 rw
             } else {
                 // 9 = `try `
```

But all I did there was change "do catch" to "try", so maybe that was just enough to make the line short enough as a single line now?

**Comment by zachlute** [comment]
Apparently running rustfmt changed all the line endings again? For real? This is a comedy of errors.

**Comment by zachlute** [comment]
I don't think the Travis failures are related to this change.

**Comment by topecongiro** [comment]
Thank you!

**Pull request merged**
