### PR TITLE
Lookup the last element of 'subexpr_list' instead of the first one

### LINKED ISSUE #1389: Poor formatting with method chains and '?' operator
Using rustfmt 0.8.0, I write this:

    let names = String::from_utf8(names)?.split('|').map(str::to_owned).collect();

and formatting turns it into

```
let names = String::from_utf8(names)
    ?
    .split('|')
    .map(str::to_owned)
    .collect();
```

instead of

```
let names = 
    String::from_utf8(names)?.split('|').map(str::to_owned).collect();
```

which is how it gets formatted if I omit the "?" operator. And I have checked: increasing max_width in rustfmt.toml has no effect.

### PR DESCRIPTION
**Pull request by topecongiro**
This commit closes #1389. `subexpr_list` is constructed in a FILO manner, so if
we want to know whether the first connector is `?` or not, we must look at the
tail of the `subexpr_list`.

### CODE REVIEW

**Comment by nrc** [comment]
Thank you for the PR! Could you add a test for this please? The example from #1389 would be fine.

**Comment by topecongiro** [comment]
@nrc Thanks. I will add a test shortly.

**Comment by topecongiro** [comment]
It seems that this PR also closes #1434. Would it be better to add a test for this issue too?

**Comment by nrc** [comment]
@topecongiro yes, that sounds good, thanks!

**Comment by nrc** [comment]
Thanks for this, its great to close off a bunch of those issues.

**Pull request merged**
