### PR TITLE
Add source/target tests for each config option

### PR DESCRIPTION
**Pull request by regexident**
Based on PR https://github.com/rust-lang-nursery/rustfmt/pull/1474 I created isolated source/target test files for each config option.

120 tests in total.

Search for `FIXME:` for possible malformatting related to:

1. [`fn_args_density = "CompressedIfEmpty"` appears to be broken in rustfmt](https://github.com/rust-lang-nursery/rustfmt/issues/1483)
2. [`where_indent` appears to be ignored completely by rustfmt](https://github.com/rust-lang-nursery/rustfmt/issues/1484)
3. [`where_density = "Vertical"` behaves like `where_density = "Tall"`](https://github.com/rust-lang-nursery/rustfmt/issues/1485)

I wasn't sure where to put the tests (if they should go into a subdir), so please feel free to recommend a different location, or just move then yourself. 🙂

### CODE REVIEW

**Comment by nrc** [comment]
Wow, lots of tests, nice!

I think it would be good to put these in a subdirectory of source/target - I think this should Just Work, but I'm not 100% sure, it might need a little hacking of the test infra. If it is a lot of work, then we can just leave them here.

**Comment by regexident** [comment]
> Wow, lots of tests, nice!

Yeah, I figured the guide's material would make for a great secondary use. :wink:

> I think it would be good to put these in a subdirectory of source/target - I think this should Just Work, but I'm not 100% sure, it might need a little hacking of the test infra. If it is a lot of work, then we can just leave them here.

As a first attempt I put a test file in a subdir, but couldn't get it to be recognized, so I opted for the prefix. In the long run they would be better of in a subdir, though, I think. Especially as with time tests will only get more, not fewer.

I am however not too familiar with how exactly the test runner for these works in rustfmt.

**Comment by nrc** [comment]
OK, lets add them here for now, I filed https://github.com/rust-lang-nursery/rustfmt/issues/1492 to put them in a subdir.

**Comment by regexident** [comment]
Cool! 👍

**Pull request merged**
