### PR TITLE
Add suport for extern types.

### PR DESCRIPTION
**Pull request by plietar**
See https://github.com/rust-lang/rust/pull/44295

### CODE REVIEW

**Comment by plietar** [comment]
If I understand correctly this needs a new branch for rustfmt and rls, so rustc can point at them

**Comment by nrc** [comment]
This is on the extern-type branch, and the RLS branch is rustfmt-extern-type.

**Comment by plietar** [comment]
Thanks @nrc. I think you forgot to push to rls tough, the rustfmt-extern-type branch is currently even with master

**Comment by nrc** [comment]
@plietar ah crap, sorry about that. Branch is now upstream.

In reply to your irc question, you can either commit after updating the submodule (commit in the Rust root) or you can set submodules=false in config.toml to stop rustbuild updating the submodules at all.

**Comment by topecongiro** [comment]
This PR has been merged, closing.

**Pull request closed without merging**
