### PR TITLE
Trailing commas for wildcard arms

### LINKED ISSUE #741: Add an option to not add a trailing comma to the wildcard arm
By the wildcard arm, I mean `_ => ...`. Trailing commas are wanted because one wants to add new arms below without touching old arms. But the wildcard arm is necessarily the last arm and no new arms will be added below.

This is similar to #712 but different.

I observed this to be an existing practice while going through Manishearth/rust-clippy#540.

### PR DESCRIPTION
**Pull request by sanxiyn**
Fix #741.

### CODE REVIEW

**Comment by nrc** [comment]
This should be an option, and default should be with trailing commas.

**Comment by nrc** [comment]
Ah, sorry, it is an option, but it should be true by default.

**Comment by nrc** [comment]
looks good, otherwise

**Comment by sanxiyn** [comment]
Done again without changing the default. Also added a test.

**Comment by sanxiyn** [comment]
What is the right forum to discuss (ok, bikeshed) the default style used by rustfmt? Because I feel rather strongly that the default should change here.

**Comment by nrc** [comment]
Thanks!

At the moment there is no such forum, I've been putting it off until Rustfmt is more complete, although we're rapidly approaching the point where it is reasonable to discuss. To be honest I'm not sure what a good venue is. I'd though RFCs, but I don't want to weight the RFCs repo down with a billion style RFCs. Suggestions are welcome! I'll try and establish something early this year (say q1, give or take).

**Comment by sanxiyn** [comment]
How about https://internals.rust-lang.org/c/guidelines/style?

**Pull request merged**
