### PR TITLE
Fix handling of code that is annotated with rustfmt::skip.

### LINKED ISSUE #3105: skipped code in macro defintion is right shifted
Tested with
- 075aa909cd2bcdc603f45e0b65119c6a7e3b2030.
- rustfmt 0.99.5-nightly (a0d1f171 2018-10-13)

With default config parameters, the `simd_shuffle16` call is right shifted. This was seen in https://github.com/rust-lang-nursery/stdsimd/blob/f37d6e731a2e7aff51d80853c0c1a710fdd7598e/coresimd/x86/avx2.rs#L2781.

```rust
pub unsafe fn _mm256_shufflehi_epi16(a: __m256i, imm8: i32) -> __m256i {
    let imm8 = (imm8 & 0xFF) as u8;
    let a = a.as_i16x16();
    macro_rules! shuffle_done {
        ($x01:expr, $x23:expr, $x45:expr, $x67:expr) => {
            #[cfg_attr(rustfmt, rustfmt_skip)]
            simd_shuffle16(a, a, [
                0, 1, 2, 3, 4+$x01, 4+$x23, 4+$x45, 4+$x67,
                8, 9, 10, 11, 12+$x01, 12+$x23, 12+$x45, 12+$x67
            ]);
        };
    }
}
```

```diff
     macro_rules! shuffle_done {
         ($x01:expr, $x23:expr, $x45:expr, $x67:expr) => {
             #[cfg_attr(rustfmt, rustfmt_skip)]
-            simd_shuffle16(a, a, [
-                0, 1, 2, 3, 4+$x01, 4+$x23, 4+$x45, 4+$x67,
-                8, 9, 10, 11, 12+$x01, 12+$x23, 12+$x45, 12+$x67
-            ]);
+                        simd_shuffle16(a, a, [
+                            0, 1, 2, 3, 4+$x01, 4+$x23, 4+$x45, 4+$x67,
+                            8, 9, 10, 11, 12+$x01, 12+$x23, 12+$x45, 12+$x67
+                        ]);
         };
     }
 }
```

### PR DESCRIPTION
**Pull request by scampi**
A rustfmt::skip'ed block is indented although original lines are
returned. In order to resolve this, the leading whitespaces are trimmed
on each line while retaining the layout; this leaves the skipped code
to be indented as necessary by the caller.

Close #3105

### CODE REVIEW

**Comment by topecongiro** [comment]
Hmm, actually I am not sure if rustfmt is allowed to change the indentation of items under `rustfmt_skip`.
cc @nrc

**Comment by scampi** [comment]
@topecongiro at first I thought keeping the layout was enough but indeed I realise now there could be situations where even indenting the code with the rest would be unwanted.

Maybe a better fix would be to not change the indentation **at all**:
- the _source_ tests added in the PR should remain as is, i.e., the skipped methods shouldn't be indented with the rest
- the method from the original issue shouldn't right-shifted either

what do you think ?

**Comment by scampi** [comment]
@topecongiro at first I thought keeping the layout was enough but indeed I realise now there can be situations where even indenting the code with the rest would be unwanted.

Maybe a better fix would be not to change the indentation **at all**:
- the _source_ tests added in the PR should remain as is, i.e., the skipped methods shouldn't be indented with the rest
- the method from the original issue shouldn't right-shift either

what do you think ?

**Comment by otavio** [comment]
@scampi, I agree. If something is marked as `rustfmt::skip` it must be kept unchanged.

**Comment by scampi** [comment]
@topecongiro @otavio thanks for your input.  Just proposing the changes now to know if that is a good direction. The solution I have found is to keep track of skipped lines which allows caller code to act on those accordingly. Those lines are stored as a list of ranges.

In addition to skipped lines, this list could also be used to keep track of lines that could not be formatted and where the original lines were used instead, e.g., the issue https://github.com/rust-lang-nursery/rustfmt/pull/3045.

**Comment by nrc** [comment]
> Hmm, actually I am not sure if rustfmt is allowed to change the indentation of items under rustfmt_skip.

I think we should not change the indentation at all, since it is possible to make the lines overrun the max width. The user can change the indentation manually and then we'll preserve it.

**Comment by nrc** [comment]
I'm unclear now - is this intended to fit `rustfmt::skip`ed code? And how is that related to macros?

**Comment by nrc** [comment]
Thank you!

**Comment by topecongiro** [comment]
@scampi My apologies for the late reply. Thank you for your work and updates!

**Comment by scampi** [comment]
no worries @topecongiro

**Pull request merged**
