### PR TITLE
CI: only run unit tests for `crater`

### PR DESCRIPTION
**Pull request by otavio**
Refs: https://github.com/rust-lang-nursery/crater/issues/358

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

### CODE REVIEW

**Comment by pietroalbini** [comment]
It's probably better to test Crater without running the integration tests (just the unit tests): they require a full Crater environment, which means building and running Docker images.

**Comment by otavio** [comment]
> It's probably better to test Crater without running the integration tests (just the unit tests): they require a full Crater environment, which means building and running Docker images.

In this case, it seems Crater is not a good option to test `rustfmt`. If @nrc agrees, I'd better remove it from integration test list.

**Comment by nrc** [comment]
> What do you think @nrc? Should we remove it from integration test list?

The best thing to do would be to run with cargo build instead of cargo test, but I think that would mean writing a new integration test script. Failing that, just removing crater seems fine.

**Comment by pietroalbini** [comment]
You need to use `cargo test --lib`, not `cargo test`.

**Comment by nrc** [comment]
Thanks!

**Pull request merged**
