### PR TITLE
scale WidthHeuristics by max_width

### LINKED ISSUE #2206: Use width relative to `max_width` for `WidthHeuristics`
```rust
#[derive(Deserialize, Serialize, Clone, Debug)]
pub struct WidthHeuristics {
    // Maximum width of the args of a function call before falling back
    // to vertical formatting.
    pub fn_call_width: usize,
    // Maximum width in the body of a struct lit before falling back to
    // vertical formatting.
    pub struct_lit_width: usize,
    // Maximum width in the body of a struct variant before falling back
    // to vertical formatting.
    pub struct_variant_width: usize,
    // Maximum width of an array literal before falling back to vertical
    // formatting.
    pub array_width: usize,
    // Maximum length of a chain to fit on a single line.
    pub chain_width: usize,
    // Maximum line length for single line if-else expressions. A value
    // of zero means always break if-else expressions.
    pub single_line_if_else_max_width: usize,
}
```

Currently we use fixed default values for these values (e.g. `fn_call_width = 60`).
We should make them default to relative values with `max_width` (e.g. `fn_call_width = max_width * 0.6` or something).

### PR DESCRIPTION
**Pull request by PSeitz**
Fixes #2206

### CODE REVIEW

**Comment by PSeitz** [comment]
Did you mean to round the max_width_ratio to the nearest 0.1? max_width is already usize

**Comment by nrc** [comment]
> Did you mean to round the max_width_ratio to the nearest 0.1? max_width is already usize

Yeah I did, sorry

> Why not just scale it linearly?

I think one of the downsides of this change is that currently if you have code where all lines are <=80 chars long, then the code will be formatted the same whether the max width is 80 or 100. With this change we lose that consistency. That seems a fine trade-off. However, where the max width is very close, it would be nice to keep that property, e.g., changing from 100 to 99 (somewhat common because some people care about fitting in a console window or diff of n chars, so need an n-1 max width). Since a line of exactly 100 chars is rare, in most cases formatting at 99 or 100 will give the same output, but stepping rather than scaling linearly we preserve that consistency.

**Comment by nrc** [comment]
I think your rebase has gone wrong - you've created a completely new file rather than modifying existing ones.

**Comment by PSeitz** [comment]
Ah, I didn't notice the file was moved. I added a rounding to 0.1 for max_width_ratio.

**Comment by nrc** [comment]
Thanks!

**Pull request merged**
