### PR TITLE
config: Change default write mode to overwrite

### PR DESCRIPTION
**Pull request by kamalmarhubi**

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
This pull request is to get an idea of what the blockers are for trusting `rustfmt` to overwrite by default.

**Comment by nrc** [comment]
I think this is the way forward, but I don't think we should change from emitting backups to not doing so in one big step. Perhaps we should warn users with a message for a few weeks and then change? Not really sure about the best way to do it - any ideas?

**Comment by kamalmarhubi** [comment]
One thing I've been thinking: introduce a global config similar to ~/.gitconfig, which can have a write-mode setting. Probably write-mode is the only thing that makes sense there so far: I don't like the idea of rustfmt formatting differently with the same project config file. Allowing formatting settings in there would let that happen.

The process could then be:
1. add facility to lookup global config, and respect any write-mode setting contained therein
2. start to warn users who do not have a global config with write-mode that it will change soon
3. switch default write-mode to overwrite

**Comment by kamalmarhubi** [comment]
We could get inspiration from how git changed the `push.default` setting in 2.0:

```
warning: push.default is unset; its implicit value is changing in 
Git 2.0 from 'matching' to 'simple'. To squelch this message 
and maintain the current behavior after the default changes, use: 

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use: 

  git config --global push.default simple
```

I think they keep the warning until you set the setting though, which we may not want to do.

**Comment by nrc** [comment]
re ~/.gitconfig, see also #837

**Comment by nrc** [comment]
I like the idea of this approach (following the git push change). I think that to start with the global/per-user config file should be separate from the per-project file, i.e., have completely separate options with different names and the file should have a different name. Then we don't need to worry about whether the per-user or per-project file takes precedence, etc. We can just use it for stuff like this.

**Comment by kamalmarhubi** [comment]
Great! This PR has served its purpose with finding the way forward. I'm closing it and have opened #871.

**Pull request closed without merging**
