### PR TITLE
Update rustc-ap-* to 272.0.0

### PR DESCRIPTION
**Pull request by otavio**
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Can we make sure the `rustc-ap` version used is compatible with the one used by the other tools of the rustc repo? Otherwise there will be conflicts when updating the rustfmt submodule.

**Comment by otavio** [comment]
Sure, it makes sense but there is a place where this is listed?

**Comment by matthiaskrgr** [comment]
https://github.com/rust-lang/rust/blob/master/src/Cargo.lock search for "rustc-ap-".

**Comment by otavio** [comment]
> https://github.com/rust-lang/rust/blob/master/src/Cargo.lock search for "rustc-ap-".

Looking at it, it seems the two dependencies using it is `rustfmt` and `racer`. It makes more sense I just do a PR for `racer` as well and bump it all.

**Comment by nrc** [comment]
> Looking at it, it seems the two dependencies using it is rustfmt and racer. It makes more sense I just do a PR for racer as well and bump it all.

I generally don't worry about keeping them in sync until we're ready to do a release, then I'll update Rustfmt and Racer to the same version, update the version of Racer in RLS and then pull the Rustfmt and RLS submodules into Rust at the same time

**Pull request merged**
