### PR TITLE
Build with rust nightly. ExprKind::Catch is now ExprKind::TryBlock.

### PR DESCRIPTION
**Pull request by zachlute**
Noticed I couldn't build today, so I fixed it.

### CODE REVIEW

**Comment by zachlute** [comment]
This fixes the rustfmt build but not the tests, obviously. Changing the tests to use `try` instead of `do catch` causes them to fail to build with things like:

```
error: expected one of `,` or `}`, found `(`
 --> tests/source\catch.rs:5:12
  |
5 |         foo()?
  |            ^ expected one of `,` or `}` here
```

So it's pretty clear it's not as simple as that, and I may be out of my depth on this one. :)

**Comment by topecongiro** [comment]
Thank you for the PR! Unfortunately there seems to be large amount of unnecessary diffs, which makes reviewing this hard. Would you fix it please?

From [this PR](https://github.com/rust-lang/rust/pull/52602) it seems that `try` block requires edition 2018, so you probably need to add `// rustfmt-edition: Edition2018` at the top of the test file.

**Comment by zachlute** [comment]
Oh man, sorry about the diffs. No idea what happened there. I guess it's probably line endings. Adding the // rustfmt-edition lines did fix a few of my problems, though. I'll try to fix this up now. Thanks!

**Comment by zachlute** [comment]
Killing this in favor of #2965 where I DIDN'T mess up all the line endings. I'm not good enough with git yet to know how to repair this branch sanely. :)

**Pull request closed without merging**
