### PR TITLE
Change default newline style to "Native"

### LINKED ISSUE #2626: Default newline_style should be Native
The general guidance for Windows developers is to use `core.autocrlf=true`, so the default experience of running `rustfmt` on a Windows machine results in changing every single line.

It seems like the best experience would be to use `newline_style = Native` or else infer the newline style instead of changing the newline style.

### PR DESCRIPTION
**Pull request by fwalch**
I tried to fix the tests for AppVeyor, but didn't actually test on Windows before opening this PR. Also, I'm not sure if this is really the best way to do this, but it seemed to be the easiest.

Fixes #2626.

### CODE REVIEW

**Comment by aloucks** [comment]
Git for windows defaults `core.autocrlf` to `input`, regardless of the recommendation. Generally `input` creates the least amount of friction, in my experience. 

image

**Comment by fwalch** [comment]
Git for Windows defaults to `core.autocrlf=true` when I start the installer with Wine, which makes sense given the description text recommending its use and `core.autocrlf=true` being the first item in this list. Maybe in your case it remembered the value you selected from the last installation or something?

GitHub recommends `core.autocrlf=true` as well: https://help.github.com/articles/dealing-with-line-endings/

However, I am not actually using Windows and just created this PR because I was looking for an issue labeled `good-first-issue`. Probably, commenting on #2626 would be better because then the original issue author can respond.

**Comment by nrc** [comment]
Thank you!

@fwalch of you want another issue to work on, https://github.com/rust-lang-nursery/rustfmt/issues/2812 is fairly easy but should get you into the guts of Rustfmt

**Comment by ehuss** [comment]
This is going to make working on Windows difficult for me.  I never use crlf, and if I understand it this will start switching my files.  It doesn't look like there is a way to specify a global config file, either.  I think it would be nice to auto-detect, and/or have an ability to globally override settings.

**Comment by nrc** [comment]
Rustfmt searches up the directory tree for a config file, so you can put a rustfmt.toml in `C:\` (or equivalent) and Rustfmt should apply it to all your projects.

We can always change the default, if this turns out to be wrong for most users.

**Comment by ehuss** [comment]
@nrc, thanks that's what I plan to do, though I have a few different drives and vms that I'll need to cover.  BTW, I hope my tone didn't sound off, I didn't mean to sound too critical.  Just wanted to let you know it might be an issue for some.

**Comment by fwalch** [comment]
@nrc Thanks for the suggestion! Looks like someone beat me to this one, but I'll keep my eyes open.

**Pull request merged**
