### PR TITLE
discard trailing blank comments

### LINKED ISSUE #539: When converting /* */ to // style comments, don't add blank lines
e.g., 

```
-/*
-  FIXME (#3300): Should allow items to be anonymous. Right now
-  we just use dummy names for anon items.
- */
+//
+// FIXME (#3300): Should allow items to be anonymous. Right now
+// we just use dummy names for anon items.
+//
```

### PR DESCRIPTION
**Pull request by scampi**
close #539

### CODE REVIEW

**Comment by scampi** [comment]
The `packed_simd` build fails with the following. However, it is strange that all but the first line of the comment is indented to begin with; I feel it shouldn't be indented.

It seems related to https://github.com/rust-lang-nursery/rustfmt/issues/2917

```diff
Diff in /home/yfful/documents/code/rustfmt/packed_simd/src/api/from/from_vector.rs at line 18:
         }
 
         // FIXME: `Into::into` is not inline, but due to
-                                                // the blanket impl in `std`, which is not
-                                                // marked `default`, we cannot override it here with
-                                                // specialization.
-                                                /*
-                                                impl Into<$id> for $source {
-                                                    #[inline]
-                                                    fn into(self) -> $id {
-                                                        unsafe { simd_cast(self) }
-                                                    }
-                                                }
-                                                */
+                                                        // the blanket impl in `std`, which is not
+                                                        // marked `default`, we cannot override it here with
+                                                        // specialization.
+                                                        /*
+                                                        impl Into<$id> for $source {
+                                                            #[inline]
+                                                            fn into(self) -> $id {
+                                                                unsafe { simd_cast(self) }
+                                                            }
+                                                        }
+                                                        */
 
         test_if!{
             $test_tt:
Diff in /home/yfful/documents/code/rustfmt/packed_simd/src/api/reductions/min_max.rs at line 41:
                     target_arch = "arm",
                     all(target_arch = "x86", not(target_feature = "sse2")),
                     target_arch = "powerpc64",
-                ),))]
+                )))]
                 {
                     use llvm::simd_reduce_min;
                     let v: $ielem_ty = unsafe { simd_reduce_min(self.0) };
```

**Comment by nrc** [comment]
> The packed_simd build fails with the following

Is this a new issue? It doesn't look like it should be caused by your patch, but if it is, it would be good not to and to add this as a test.

**Comment by nrc** [comment]
And the code looks great, thanks!

**Comment by scampi** [comment]
With the [latest packed_simd](https://github.com/rust-lang-nursery/packed_simd/commit/8d991007e0d23a5a2ecce22f4772bcdab26b48d7) master, I don't see anymore differences in `packed_simd`, but it was happening up to commit  https://github.com/rust-lang-nursery/packed_simd/commit/1a6450d9f31ad7b42042ca4c18c4b05dff5e75ea.

It is interesting to note that the indentation of that commented code increased already in a previous commit https://github.com/rust-lang-nursery/packed_simd/commit/0cab9e92b6d9f7294b391864be833e09a39f1bc3#diff-a70485da056880cc8fbf5e1bd3cb33fa

Although that indentation shift is not due to a change in this PR, should I open an issue for it though ? The indentation should not increase and stay at the `// FIXME` column I guess.

The problem with `rand` still occurs: it's an extra comma:

```diff
Diff in /home/yfful/documents/code/rustfmt/rand/src/rngs/entropy.rs at line 290:
         all(target_arch = "wasm32", feature = "stdweb"),
         all(target_arch = "wasm32", feature = "wasm-bindgen"),
     ),
-)))]
+),))]
 type Os = NoSource;
 
 type Custom = NoSource;
```

**Comment by nrc** [comment]
> should I open an issue for it though ?

Yes please!

**Pull request merged**
