### PR TITLE
update readme to use `--write-mode=check` instead of `--check`

### PR DESCRIPTION
**Pull request by soenkehahn**
`--check` just gives me:

```
Unrecognized option: 'check'
```

@data-pup

### CODE REVIEW

**Comment by nrc** [comment]
The docs are correct, I think you must be using an old version of Rustfmt - are you using rustup?

**Comment by soenkehahn** [comment]
Yeah, I was installing `rustfmt` with the recommended command from this readme (`rustup component add rustfmt-preview`). Which leaves me with this:

```
$ rustfmt --version
rustfmt 0.6.1-stable (49279d7 2018-05-08)
```

**Comment by nrc** [comment]
Then it is just that the changes haven't landed on stable yet. The README matching the stable tag is correct, although that is a little deeper than one ought to dig

**Comment by soenkehahn** [comment]
Ah, I see. Thanks for explaining. (I don't know enough about how `stable` and `nightly` are managed in this repo to suggest a good solution here...)

**Pull request closed without merging**
