### PR TITLE
config: Disable report_todo by default

### PR DESCRIPTION
**Pull request by kamalmarhubi**

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
I don't even think the feature belongs in rustfmt, but at the very least it should be off by default.

**Comment by nrc** [comment]
The motivation for this feature is parity with `make tidy`. Apart from that, I think it is good engineering practice to have an enforced separation of `TODO` and `FIXME`, the former meant to be temporary while a patch is written, the latter is allowed to land. This is a check on landing incomplete code.

I'm sympathetic to the argument that this is not really formatting, as such and so shouldn't be on by default, but I can't think of a better place for it to live and I don't believe there is more motivation for turning it off rather than leaving it on.

Do you have a use case for why it should be off by default?

I'm curious what others think about this too.

**Comment by kamalmarhubi** [comment]
**Why it should be off by default:** `TODO` is a convention used in many ways by many projects. Forcing an interpretation* is not the place of a formatting tool. Some examples of projects / organizations with different interpretations from the one in rustfmt:
- [Google C++ style guide](https://google.github.io/styleguide/cppguide.html#TODO_Comments): ‘Use `TODO` comments for code that is temporary, a short-term solution, or good-enough but not perfect.’
- [Cap'n Proto style guide](https://github.com/sandstorm-io/capnproto/blob/320ac36b282f6c9417017eaeca9269229ae6fb74/style-guide.md#comments): ‘release scripts can error out if release-blocking `TODO`s are present.’

**Why it shouldn't be in rustfmt:**: rustfmt is a *formatting* tool: it takes code in, and spits out better formatted code that abides by conventions. Reporting style deviations belongs in a lint tool.


* yes, a formatting tool is all about enforcing conventions. However, these are syntactic rather than semantic; enforcing an interpretation of `TODO` leans more towards semantic. :-)

**Comment by kamalmarhubi** [comment]
Also, rustfmt currently gives 18 such warnings on its own code base!

**Comment by cassiersg** [comment]
I agree rustfmt is not the ideal place to have this kind of lints. Maybe it is better to have that is clippy ?

**Comment by kamalmarhubi** [comment]
clippy requires nightly which makes it a more difficult tool to recommend. I think a separate tool would make sense. Not sure if there is an existing rustlint but it would make sense I think. In the meantime, I'd just like this disabled :-)

**Comment by kamalmarhubi** [comment]
ping :-)

**Comment by nrc** [comment]
I think rustfmt probably should be the tool for doing this, but I'm ok with it not being a default.

**Comment by kamalmarhubi** [comment]
@nrc, rereading Design.md, and I saw this in there:

> My long term goal is that all style lints can be moved from the compiler to
rustfmt and, as well as warning, can either fix problems or emit refactoring
scripts to do so.

so apologies for ignoring that. I wonder if the right approach is a family of tools that share a lot of implementation?

**Comment by nrc** [comment]
Yeah, I have been considering a less monolithic vision recently. I'm not exactly how it should work  and how to make it ergonomic though.

**Pull request merged**
