### PR TITLE
Trim a trailing whitespace on empty line inside code block comment 

### LINKED ISSUE #2260: Adds trailing whitespaces to code blocks in doc comments and then complains about it
Hello

I have an example in doc comment and separate parts of the code by empty lines. I don't have trailing whitespace on the empty lines.

However, rustfmt tries to add them and then complains about them there. Even the complaint is a bit wrong, because it didn't merely *leave* them there, it *added* them. I believe both is wrong.

```diff
Diff in /home/vorner/prog/slog-retry/src/lib.rs at line 29:
 //! extern crate slog_async;⏎
 //! extern crate slog_json;⏎
 //! extern crate slog_retry;⏎
-//!⏎
+//! ⏎
 //! use std::net::TcpStream;⏎
-//!⏎
+//! ⏎
 //! use slog::Drain;⏎
-//!⏎
+//! ⏎
 //! fn main() {⏎
 //!     let retry = slog_retry::Retry::new(|| -> Result<_, std::io::Error> {⏎
 //!             let connection = TcpStream::connect("127.0.0.1:1234")?;⏎
```

```
error: left behind trailing whitespace
  --> /home/vorner/prog/slog-retry/src/lib.rs:32
   |
32 | //! 
   |    ^

error: left behind trailing whitespace
  --> /home/vorner/prog/slog-retry/src/lib.rs:34
   |
34 | //! 
   |    ^

error: left behind trailing whitespace
  --> /home/vorner/prog/slog-retry/src/lib.rs:36
   |
36 | //! 
   |    ^
```

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #2260.

### CODE REVIEW

**Comment by gnzlbg** [comment]
`cargo install rustfmt-nightly` does not have this fix yet, does anybody know how long does that take?

**Comment by topecongiro** [comment]
0.3.0 was published this morning, so I think it would take another week or two. Would you please `cargo install --git https://github.com/rust-lang-nursery/rustfmt --force` for now?

**Comment by gnzlbg** [comment]
Thanks for the quick response. We are using it in the CI of `rust-lang-nursery/stdsimd` so I if we change that in CI we end up requiring the same version from all contributors. We were expecting `rustfmt-nightly` to be sporadically broken for one day or two every now and then but nothing in the one to two weeks time frame. 

Ideally I'd like to fix a rustfmt version in the rustfmt.toml or Cargo.toml files and have cargo fmt automatically use that version.

**Comment by topecongiro** [comment]
@gnzlbg 

> We were expecting rustfmt-nightly to be sporadically broken for one day or two every now and then but nothing in the one to two weeks time frame.

This makes sense. I published 0.3.1.

> Ideally I'd like to fix a rustfmt version in the rustfmt.toml or Cargo.toml files and have cargo fmt automatically use that version.

This is possible via `required_version` config option. e.g. in rustfmt.toml,
```toml
required_version = "0.3.1"
```

**Comment by gnzlbg** [comment]
Awesome, thanks!

**Comment by gnzlbg** [comment]
@topecongiro the docs of `required_version` are a bit scarce, but it seems that `cargo fmt` fails if a particular `rustfmt` version is not used (as opposed to installing the corresponding version and using that).

**Comment by gnzlbg** [comment]
@topecongiro another question, `cargo install rustfmt-nightly --version a.b.c --force` compiles a `rustfmt` from source. Is this guaranteed to never break? Or do I need an appropriate nightly toolchain to do that?

**Comment by topecongiro** [comment]
>  another question, cargo install rustfmt-nightly --version a.b.c --force compiles a rustfmt from source. Is this guaranteed to never break? Or do I need an appropriate nightly toolchain to do that?

It is not guaranteed. Different version means that rustfmt may be using different AST internally. So you need an appropriate nightly toolchain which uses the same AST as rustfmt.

We could possibly guarantee this once libsyntax is published on crates.io.

**Pull request merged**
