### PR TITLE
Format label break

### LINKED ISSUE #2722: Format block with label
For example,
```rust
'empty_block: {}

let result = 'block: {
    if foo() {
        break 'block 1;
    }
    if bar() {
        break 'block 2;
    }
    3
};
```
cc https://github.com/rust-lang/rfcs/blob/master/text/2046-label-break-value.md.

### PR DESCRIPTION
**Pull request by csmoe**
Fixes #2722

### CODE REVIEW

**Comment by csmoe** [comment]
Oops, made a mistake with 'label', will fix later

**Comment by topecongiro** [comment]
Thank you!

**Comment by Amanieu** [comment]
This is broken. Look at the test file: the labels are being deleted.

**Comment by zesterer** [comment]
Any update on when this might be fixed, or whether help is needed in fixing this? We're having similar problems with our nightly codebase.

**Comment by Amanieu** [comment]
@zesterer You need to update your nightly. This has been fixed for a while: https://github.com/rust-lang/rust/pull/51739

**Comment by zesterer** [comment]
@Amanieu Aha, thank you!

**Pull request merged**
