### PR TITLE
deps: Update syntex_syntax to 0.29.1

### PR DESCRIPTION
**Pull request by kamalmarhubi**

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
Opened #849 to fix nightly build.

**Comment by kamalmarhubi** [comment]
Rebased to pick up #843.

**Comment by nrc** [comment]
Thanks! (And sorry for the slow review - vacation).

**Comment by kamalmarhubi** [comment]
No worries! I hope you enjoyed the vacation :-)

**Pull request merged**
