### PR TITLE
Remove unnecessary rewriting

### PR DESCRIPTION
**Pull request by topecongiro**
This PR removes unnecessary rewriting to solve the performance issue.

### CODE REVIEW

**Comment by topecongiro** [comment]
So as reported in #1849, rustfmt has been getting slower and slower (mostly due to my fault).
IMO, there are several reasons for this:
1. In some places, rustfmt rewrites an expression in several ways and choose the best one among them. This does no harm when the expression is simple, but when it gets complex (e.g. a sequence of closure + chain) and requires a lot of rewriting, this trial-and-error strategy could easily sum up to poor performance.
2. rustfmt has been trying to recover missing comments in more places. This is nice, but to this end it requires a lot of small string allocation, which could hurt the performance.

This PR tries to solve the first issue by removing unnecessary rewriting when rewriting 1. the last argument of function call and 2. the last element of chain.
Currently, in these two places, rustfmt rewrites the expression on its own line for the first time, and for the second time rewrites it with overflow, and choose the better candidate:
```rust
// First rewrite
foo(
    aaaa, 
    bbbb, 
    cccc, 
    dddd,
    |x| {
        let y = x + 1;
        y
    },
)
// Second rewrite
foo(aaaa, bbbb, cccc, dddd, |x| {
    let y = x + 1;
    y
})
```
Since we favour the overflowed version, this PR changes this to first rewrite with overflow, and if it succeeds, use it without rewriting further. This new strategy avoids rewriting twice in complex cases.

**Comment by topecongiro** [comment]
Roughly measured performance:

||rls-analysis|
|-|-|
|master|8.0s|
|PR|0.4s|

**Comment by nrc** [comment]
This fantastic, thank you! Can be merged after a rebase.

**Comment by topecongiro** [comment]
Rebased to resolve conflicts.

**Pull request merged**
