### PR TITLE
Allow single line block in expression context

### LINKED ISSUE #1714: Formatting of {v}.split_at_mut(mid)
The following code:

```rust
v = &mut {v}[mid..];
let (left, right) = {v}.split_at_mut(mid);
```

gets formatted to:

```rust
v = &mut {
    v
}[mid..];
let (left, right) = {
    v
}.split_at_mut(mid);
```

Perhaps we need a rule saying that if a single identifier is inside the braces, it shouldn't be treated as a multiline code block?

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #1714.

### CODE REVIEW

**Comment by nrc** [comment]
I think that `unsafe` blocks should still be single-lined, even in statement context. For non-unsafe blocks in expression context, I would like to distinguish between sub-expressions and top-level expressions, and we should only single-line in the former case. Otherwise you get something like:

```
fn foo() {
    {
        bar()
    }
    { bar() }
}
```

Which looks odd to me (I would expect the blocks to be formatted in the same way).

**Comment by topecongiro** [comment]
Thank you for your comments!
To summarize,

1. `unsafe` can be single-lined whenever possible.
2. Non-unsafe block can be single-lined if it appears in sub-expression context and not in statement, control flow block or top-expression context.

For example,
```rust
fn main() {
    // right
    {
        {
            {
                {}
            }
        }
    }
    // wrong
    {
        { { {} } }
    }

    // right
    let x = { 3 };
    // wrong
    let x = {
        3
    };

    // right
    match x {
        Some(y) => {
            println!("{}", y)
        }
        None => {
            println!("None")
        }
    }
    // wrong
        match x {
        Some(y) => { println!("{}", y) }
        None => { println!("None") }
    }
}
```

The last case is only relevant when `wrap_match_arms = false` (although I am not sure if this config option is working as intended).

**Comment by nrc** [comment]
Pretty much yes, the only one I'm unsure about is:
```
let x = { 3 };
```
Technically that is expression position, not sub-expression position because it is nested inside a statement rather than an expression, but it does seem a bit odd to format `let x = { 3 };` differently to `x = { 3 };`, so I think I agree with you.

**Comment by topecongiro** [comment]
Thanks! Updated and rebased to reflect the feedback.

**Comment by topecongiro** [comment]
Added a commit to fix a typo from 90251c32ff4b52e3f3ac466d1b16bb91366d21a3 😁 .

**Comment by nrc** [comment]
Thank you!

**Pull request merged**
