### PR TITLE
Expose FileLines JSON representation

### PR DESCRIPTION
**Pull request by Xanewok**
Blocks https://github.com/rust-lang-nursery/rls/pull/990.

r? @nrc

### CODE REVIEW

**Comment by nrc** [comment]
lgtm, but seems to be failing a test

**Comment by Xanewok** [comment]
Ah right, this will need some defined ordering. My bad, on it!

**Comment by topecongiro** [comment]
AFAICT the error is unrelated to this PR, possibly due to #2900 (unfortunately, rustfmt cannot remove the trailing comma because, _in theory_, that could change the semantic of the original code).

**Comment by Xanewok** [comment]
Is there anything else I can do to get this merged? Is the tree closed until CI is all green again?

**Comment by nrc** [comment]
Nah, I was just on planes, etc. Thanks for the PR!

**Pull request merged**
