### PR TITLE
Preserve trailing two whitespace in comments

### LINKED ISSUE #2434: Preserve trailing whitespace in doc comments
# Situation:
I found that rustfmt do format the documentation comments in doctumentations.
# For example:
Some space which are required by Markdown to wrap will be deleted.
Original text:
```rust
/// This is content which contains to space in the end!  
```
rustfmt will delete these two spaces and documentations' format will be **terrible.**

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #2434.

### CODE REVIEW

**Comment by topecongiro** [comment]
This PR just treats two-spaces as a special case. I prefer to do this over not removing trailing whitespaces at all in comments. Do you have any thoughts @nrc?

**Comment by nrc** [comment]
I think we should continue to trim two spaces from code or comment lines and only preserve them in doc comments.

I'm not clear on the markdown semantics - if there are 3 or more spaces, does this have the same effect as 2? If so then we should not trim for >= 2 spaces, not just exactly 2 spaces.

**Comment by LEXUGE** [comment]
But if there are two more space in the code?
For example:
```rust
let foo = bar;                                                         // Many space
```
Or just two space at the end of the line?
I haven't read the rustfmt's code yet. But I think we may treat the whole markdown (`///` and `//!`) as a special case.

**Comment by topecongiro** [comment]
It looks like rustdoc treats two or more trailing spaces as a line break. I will update this PR accordingly.

**Comment by topecongiro** [comment]
cc #37.

This PR fixes the issue only when using the default setting. We need another PR for #37 when `wrap_comments` or `normalize_comments` is set to `true`.

**Comment by nrc** [comment]
Thank you!

**Comment by LucianoBestia** [comment]
I  tried this on nightly version rustfmt 1.3.0-nightly (d3345024 2019-06-09).

rustfmt preserves trailing double space in doc-comments that begin with `//!` 
But it does not preserve it in **multiline doc-comment** that begin with `/*!`
example:
```
/*! some text  
with trailing double space  
for markdown newline formatting  
*/
``` 
Writing or copy/paste long markdown text without having //! on each line is much easier.

**Pull request merged**
